---
  # Title: app-ms-dynamics-nav2017-client
  #
  # Author: Luc Rutten
  # Version: 1.0
  #
  # Description: Install MS Dynamics NAV2017 client on Endpoint
  # File: tasks/windows-amd64.yml 


  - name: "Check if package is already installed before downloading installation files. (32bit)"
    win_reg_stat:
      path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\"{{ pkg_product_id }}"
    register: pkg_isinstalled
    when:
      - pkg_arch == '32bit'

  - name: "Check if package is already installed before downloading installation files. (64bit)"
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\"{{ pkg_product_id }}"
    register: pkg_isinstalled
    when:
      - pkg_arch == '64bit'

  - name: "Create local Ansible repository"
    win_file:
      path: "{{ pkg_repo_local }}"
      state: directory
    when:
      - pkg_isinstalled.exists == 'false'

  - name: "Download Package"
    win_get_url:
      url: "{{ pkg_repo_remote }}"
      dest: "{{ pkg_repo_local }}/{{ pkg_name }}"
      force: no
    when:
      - pkg_isinstalled.exists == 'false'

  - name: "Unzip package"
    win_unzip:
      src: "{{ pkg_repo_local }}/{{ pkg_name }}"
      dest: "{{ pkg_repo_local }}"
    when:
      - pkg_isinstalled.exists == 'false'

  - name: "Installing {{ pkg_name }}"
    win_package:
      path: "{{ pkg_installer }}"
      product_id: "{{ pkg_product_id }}"
      arguments: "{{ pkg_arguments }}"
      state: present
    when:
      - pkg_isinstalled.exists == 'false'

  - name: "Removing installation files"
    win_file:
      path: "{{ pkg_repo_local }}"
      state: absent
    when:
      - pkg_isinstalled.exists == 'false'
